spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jdbc
    username: root
    password: admin
    dirver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 5
    max-idle: 2